### ISSUE TITLE
[BUG] ignition-docker-iiot doesn't install modules

### ISSUE THREAD

**Issue by etknorr** [design-group/ignition-docker-legacy#58]
**Describe the bug**
When running a docker-compose file with env flag `IIOT_MODULES_ENABLED: mqtt-transmission,mqtt-engine,mqtt-distributor`, modules are not installed on the gateway on `docker-compose up -d` as expected

**To Reproduce**
1. docker-compose.yml
```yml
services:
  broker:
    image: bwdesigngroup/ignition-docker-iiot:8.1.24  # I also tried 8.1.21 and 8.1.24 with same result. checksums should have been updated for 8.1.24 before last release
    hostname: broker-mqtt
    ports:
      - 9210:8088
    volumes:
      - ./broker-data:/workdir
    environment:
      IIOT_MODULES_ENABLED: mqtt-transmission,mqtt-engine,mqtt-distributor
```
2. `docker-compose up -d`
3. Go to gateway > Config > modules

**Expected behavior**
Upon completion of above steps, IIOT modules should be installed on gateway

**Development Environment (please complete the following information):**

    - OS: MacOS
    - Version: 12

**Additional context**
- The checksums could be bad, should check. Otherwise, I also updated for 8.1.25, I may try to build that image and see if I can get that to work. I haven't done that yet.
- @keith-gamble Did this work on 8.1.21?
